config/routes.rb
Readit::Application.routes.draw do
  devise_for :users

  resources :links do
    resources :comments
  end
  resources :pages
  root to: "pages#index"

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :message, :link_id
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url, :title, :comments
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :username
  has_many :links
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!  

  def create
    @comment = current_user.comments.create(params[:comment].merge(link_id: params[:link_id]))
    redirect_to :back
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	def show
    @link    = Link.find(params[:id])
    @comment = @link.comments.build
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    
    end  
  
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    
    params[:per_page] ||= 25
    params[:page]     ||= 1

    @links = Link.order('created_at DESC').page(params[:page].to_i).per_page(params[:per_page].to_i) 

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Readit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%# user is logged in, show log out link %>
<% if current_user.present? %>
  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
<%# user is not logged in, show signup and login links %>
<% else %>
  <%= link_to 'Sign In', new_user_session_path %> |
  <%= link_to 'Register Now!', new_user_registration_path %>
<% end %>
<%= yield %>

</body>
</html>

app/views/links/new.html.haml
= form_for(@link) do |f|
  - if @link.errors.any?
    #error_explanation
      %h2= pluralize(@link.errors.count, "error") + "prohibited this idea from being saved:"

      %ul
        - @link.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    %br
    = f.text_field :title
  .field
    = f.label :url
    %br
    = f.url_field :url

  .actions= f.submit

app/views/links/show.html.haml
%p= link_to @link.title, @link.url

= form_for [@link, @comment] do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= pluralize(@comment.errors.count, "error") + "prohibited this idea from being saved:"

      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :message
    %br
    = f.text_area :message, :placeholder => "Add a comment"

  .actions= f.submit

%br
%h2 Comments:

%div
  - @link.comments.each do |comment|
    %p= comment.message

%br
= link_to "Return Home", pages_path

app/views/pages/index.html.haml
%h2 I AMA Homepage

= link_to "Add a link", new_link_path

%ul
  - @links.each do |link|
    %li= link_to link.title, link.url
    %li= link_to "comments", link

= will_paginate @links